name: Wisecow CI/CD Pipeline

on:
  push:
    branches:
      - main   # change to your branch

jobs:
  build-and-deploy:
    name: Build and Deploy Wisecow
    runs-on: self-hosted

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and Push Docker Image
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: ${{ secrets.DOCKER_USERNAME }}/wisecow:latest

      - name: Set up kubectl
        uses: azure/setup-kubectl@v4
        with:
          version: 'latest'

      - name: Configure kubeconfig
        run: |
          mkdir -p ~/.kube
          echo "${{ secrets.KUBECONFIG }}" > ~/.kube/config
          chmod 600 ~/.kube/config

      - name: Ensure Wisecow namespace exists
        run: |
          kubectl get namespace wisecow || kubectl create namespace wisecow

      - name: Deploy to Kubernetes
        run: |
          kubectl apply -f k8s/deployment.yaml -n wisecow
          kubectl apply -f k8s/service.yaml -n wisecow
          # Optional: rollout status
          kubectl rollout status deployment/wisecow-deployment -n wisecow
